# Change these first
owner: n-balmaceda # Your GitHub organization or username, where this repository lives
repo: upptime-test # The name of this repository

sites:
  - name: Portal HIGG
    url: https://portal.higg.org
  - name: Profiles HIGG
    url: https://profiles.higg.com
  - name: Corp Reporting
    url: https://corpreporting.higg.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /upptime-test
  logoUrl: https://cdn.cookielaw.org/logos/d96286c9-3074-446f-b7cc-33793289e1d8/a53902d8-786b-4cf4-bfff-26e98ca267e8/acae450d-8663-493c-ba0b-87b513dee83e/higg-lockup-360x104.png
  name: HIGG Status Page
  introTitle: "**Higg** is an integrated software platform that helps you take responsibility for your entire impact – from materials to products, from factories to stores, from carbon emissions to working conditions."
  introMessage: Status Page
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
