# Change these first
owner: n-balmaceda # Your GitHub organization or username, where this repository lives
repo: upptime-test # The name of this repository

sites:
  - name: Scrollarmy
    url: https://scrollarmy.com.ar

status-website:
  baseUrl: /upptime-test
  name: Scrollarmy Status Page
  introTitle: "**Scrollarmy** is the best community ever"
  introMessage: Status Page
  navbar:
    - title: Status
      href: /
